version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      # comment
      - echo "Installing Prowler and dependencies..."
      - pip3 install detect-secrets
      - apt-get -y install jq
      - git clone https://github.com/toniblyx/prowler
      - cp check* prowler/checks/
      - cp group* prowler/groups/
  build:
    commands:
      - echo "Running Prowler as ./prowler $PROWLER_OPTIONS"
      - cd prowler
      - ./prowler $PROWLER_OPTIONS
  post_build:
    commands:
      - echo "Nothing to do in the post_build phase..."
reports:
  checks:
    files:
      - '**/*'
    base-directory: 'prowler/junit-reports'
    file-format: JunitXml
artifacts:
  files:
    - prowler/output/*
    - prowler/junit-reports/*
cache:
  paths:
    - /root/.cache/pip/**/*
